services:

  db:
    container_name: indexer-db
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 256mb
    env_file:
      - .env
    ports:
      - 5151:5432
    volumes:
      - indexer-data:/var/lib/postgresql
  
  redis:
    container_name: indexer-redis
    image: redis:8.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --maxmemory 128mb
      --save 30 1
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "5s"
      timeout: "3s"
      retries: 10
    volumes: 
      - indexer-redis:/data
  
  indexer:
    build:
      context: .
      dockerfile: cmd/indexer/Dockerfile
    container_name: 'indexer-indexer'
    ports:
      - 3001:3000
    env_file:
      - cmd/indexer/.env
    restart: on-failure
    networks:
      - network
    extra_hosts:                                                                           
    - "host.docker.internal:host-gateway"

  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: 'indexer-api'
    ports:
      - 3002:3000
    env_file:
      - cmd/api/.env
    restart: on-failure
    networks:
      - network
    extra_hosts:                                                                           
    - "host.docker.internal:host-gateway"


volumes:
  indexer-data:
  indexer-redis:


networks: 
  network:


