// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type Block struct {
	ID           uint64         `json:"id"`
	Hash         string         `json:"hash"`
	ParentHash   string         `json:"parentHash"`
	GasLimit     uint64         `json:"gasLimit"`
	GasUsed      uint64         `json:"gasUsed"`
	Miner        string         `json:"miner"`
	Timestamp    uint64         `json:"timestamp"`
	Transactions []*Transaction `json:"transactions"`
}

type BlockFilter struct {
	ID       *uint64 `json:"id,omitempty"`
	FromTime *uint64 `json:"fromTime,omitempty"`
	ToTime   *uint64 `json:"toTime,omitempty"`
	FromID   *uint64 `json:"fromId,omitempty"`
	Offset   *uint64 `json:"offset,omitempty"`
}

type Event struct {
	LogIndex uint64   `json:"logIndex"`
	Emitter  string   `json:"emitter"`
	Data     *string  `json:"data,omitempty"`
	Topics   []string `json:"topics"`
}

type EventFilter struct {
	Emitter *string   `json:"emitter,omitempty"`
	Topics  []*string `json:"topics"`
}

type Query struct {
}

type Transaction struct {
	Hash    string   `json:"hash"`
	From    string   `json:"from"`
	To      *string  `json:"to,omitempty"`
	GasUsed uint64   `json:"gasUsed"`
	Events  []*Event `json:"events"`
}

type TransactionFilter struct {
	To   *string `json:"to,omitempty"`
	From *string `json:"from,omitempty"`
}
