package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"github/ijusttookadnatest/indexer-evm/internal/core/domain"
	"github/ijusttookadnatest/indexer-evm/internal/handlers/graphql/graph/dto"
)

// Transactions is the resolver for the transactions field.
func (r *blockResolver) Transactions(ctx context.Context, obj *dto.Block) ([]*dto.Transaction, error) {
	return GetTransaction(ctx, obj.ID)
}

// Blocks is the resolver for the blocks field.
func (r *queryResolver) Blocks(ctx context.Context, filter *dto.BlockFilter) ([]*dto.Block, error) {
	hasId := filter.ID != nil
	hasRangeTime := filter.FromTime != nil && filter.ToTime != nil
	hasRangeId := filter.FromID != nil && filter.Offset != nil
	if hasId && hasRangeTime || hasId && hasRangeId || hasRangeId && hasRangeTime {
		return nil, fmt.Errorf("invalid params")
	}
	if !hasId && !hasRangeId && !hasRangeTime {
		return nil, fmt.Errorf("invalid params")
	}

	var blocks []domain.BlockTxs
	var block *domain.BlockTxs
	var err error

	if hasId {
		block, err = r.Service.GetBlockById(*filter.ID, false)
	} else if hasRangeTime {
		blocks, err = r.Service.GetBlocksByRangeTime(*filter.FromTime, *filter.ToTime, false)
	} else {
		blocks, err = r.Service.GetBlocksWithOffset(*filter.FromID, *filter.Offset, false)
	}
	if err != nil {
		return nil, err
	}
	if block != nil {
		blocks = []domain.BlockTxs{*block}
	}

	dtoBlocks := make([]*dto.Block, len(blocks))
	for i, block := range blocks {
		dtoBlocks[i] = toBlockDTO(block)
	}
	return dtoBlocks, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, filter *dto.TransactionFilter) ([]*dto.Transaction, error) {
	txFilter := domain.TransactionFilter{
		From: filter.From,
		To:   filter.To,
	}

	txs, err := r.Service.GetTransactionByFilter(txFilter)
	if err != nil {
		return nil, err
	}

	dtoTxs := make([]*dto.Transaction, len(txs))
	for i, tx := range txs {
		dtoTxs[i] = toTransactionDTO(tx)
	}
	return dtoTxs, nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *dto.EventFilter) ([]*dto.Event, error) {
	topics := make([]string, len(filter.Topics))
	for i, topic := range filter.Topics {
		topics[i] = *topic
	}
	eventFilter := domain.EventFilter{
		Emitter: filter.Emitter,
		Topics:  topics,
	}

	events, err := r.Service.GetEventByFilter(eventFilter)
	if err != nil {
		return nil, err
	}

	dtoEvents := make([]*dto.Event, len(events))
	for i, event := range events {
		dtoEvents[i] = toEventDTO(event)
	}
	return dtoEvents, nil
}

// Events is the resolver for the events field.
func (r *transactionResolver) Events(ctx context.Context, obj *dto.Transaction) ([]*dto.Event, error) {
	return GetEvent(ctx, obj.Hash)
}

// Block returns BlockResolver implementation.
func (r *Resolver) Block() BlockResolver { return &blockResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

type blockResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
